language: node_js

env:
  - DATABASE_URL=postgresql://sino:codex123@localhost:5432/greeted_names

node_js:  
  - "8.10.0"

before_script:
  - psql -c 'create database greeted_names;' -U postgres
  - psql -U postgres -d greeted_names -a -f tables.sql

addons:
    apt:
    packages:
    - postgresql-server-dev-9.2


services:
  - postgresql

  before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

  